// <auto-generated />
using System;
using FightingFantasy.Dal.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FightingFantasy.Dal.Migrations
{
    [DbContext(typeof(FightingFantasyDbContext))]
    [Migration("20210321173142_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("BookStat", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookId", "StatId");

                    b.HasIndex("StatId");

                    b.ToTable("BookStat");

                    b.HasData(
                        new
                        {
                            BookId = 1L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 1L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 1L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 1L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 2L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 2L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 2L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 2L,
                            StatId = 5L
                        },
                        new
                        {
                            BookId = 3L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 3L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 3L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 3L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 4L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 4L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 4L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 4L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 4L,
                            StatId = 6L
                        },
                        new
                        {
                            BookId = 4L,
                            StatId = 7L
                        },
                        new
                        {
                            BookId = 5L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 5L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 5L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 5L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 5L,
                            StatId = 8L
                        },
                        new
                        {
                            BookId = 6L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 6L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 6L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 6L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 7L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 7L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 7L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 7L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 8L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 8L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 8L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 9L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 9L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 9L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 9L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 10L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 10L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 10L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 10L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 10L,
                            StatId = 9L
                        },
                        new
                        {
                            BookId = 11L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 11L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 11L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 11L,
                            StatId = 4L
                        },
                        new
                        {
                            BookId = 12L,
                            StatId = 1L
                        },
                        new
                        {
                            BookId = 12L,
                            StatId = 2L
                        },
                        new
                        {
                            BookId = 12L,
                            StatId = 3L
                        },
                        new
                        {
                            BookId = 12L,
                            StatId = 10L
                        });
                });

            modelBuilder.Entity("FightingFantasy.Domain.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "FF1",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Your quest is to find the Warlock's treasure, hidden deep within a dungeon populated with a multitude\r\n                                 of terrifying monsters. You will need courage, determination and a fair amount of luck if you are to survive all the traps\r\n                                 and battles, and reach your goal — the innermost chambers of the Warlock's domain.</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Warlock of Firetop Mountain"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "FF2",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Who knows what monstrous creatures lie in wait in the Citadel of Chaos?</p> \r\n                <p>The Citadel holds a dark and dangerous peril for anyone foolhardy enough to venture through its gruesome gates. \r\n                And yet venture you must, for your mission lies at the heart of the Citadel, with the dread sorceror, Balthus Dire!</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Citadel of Chaos"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "FF3",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Who knows what monstrous creatures lurk in Darkwood forest?</p>\r\n                <p>Only the foolhardy would risk an encounter with the unknown perils that lurk in the murky depths of Darkwood Forest. \r\n                Yet there is no alternative, for your quest is a desperate race against time to find the missing pieces of the \r\n                legendary Hammer of Stonebridge — fashioned by Dwarfs to protect the villagers of Stonebridge against their ancient doom.</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forest of Doom"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "FF4",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>The fate of the Starship Traveller and her crew lies in YOUR hands!</p>\r\n\r\n                <p>Sucked through the nightmare of the Seltsian Void, the starship Traveller emerges at the other side of the black hole into an unknown universe. \r\n                YOU are the captain of the Traveller and her fate depends on YOU! Will you be able to discover the way back to Earth from the alien \r\n                peoples and planets you encounter, or will the starship be doomed to roam uncharted space forever?</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Starship Traveller"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "FF5",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Terror stalks the night in Silverton!</p>\r\n                <p>The prosperous town of Silverton is being held to ransom by Zanbar Bone and his bloodthirsty Moon Dogs. \r\n                YOU are an adventurer, and the merchants of Silverton turn to you in their hour of need.</p>\r\n\r\n                <p>Your mission takes you along dark, twisting streets where thieves, vagabonds and creatures of the night lie in wait to trap \r\n                the unwary traveller. And beyond lies the most fearsome adventure of them all — the tower stronghold of the infamous Zanbar Bone!</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "City of Thieves"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "FF6",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Down in the dark twisting labyrinth of Fang, unknown horrors await you!</p>\r\n                <p>Countless adventurers before you have taken up the challenge of the Trial of Champions, but not one has survived.\r\n                Devised by the devilish mind of Baron Sukumvit,the labyrinth is riddled with fiendish traps and hideous creatures of darkness \r\n                to trick and test you almost beyond the limits of endurance!",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Deathtrap Dungeon"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "FF7",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Can you save the young men of Oyster Bay from the evil Lizard Men?</p>\r\n                <p>Kidnapped by a vicious race of Lizard Men from Fire Island, the young men of Oyster Bay face a grim future of slavery, starvation \r\n                and a lingering death. Their new master is the mad and dangerous Lizard King, who holds sway over his land of mutants by the eerie \r\n                powers of black magic and voodoo. YOU are the only one who can hope to rescue the suffering prisoners, but do you have the courage \r\n                to risk this dangerous mission?</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Island of the Lizard King"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "FF8",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Nightmarish creatures lurk in the slimy depths of Scorpion Swamp!</p>\r\n\r\n                <p>You're no fool. All your life you've heard tales of Scorpion Swamp and how it is criss-crossed with treacherous paths leading to the \r\n                haunts of its disgusting denizens. One step out of place spells a certain and lingering death. But now, the swamp holds out the lure of \r\n                treasure and glory - and you cannot resist the challenge!</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Scorpion Swamp"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "FF9",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>The dreaded Snow Witch of Allansia plans to dominate the world!</p>\r\n\r\n                <p>Deep within the Crystal Caves of the Icefinger Mountains, the dreaded Snow Witch is plotting to bring on a new ice age. \r\n                A brave trapper dies in your arms and lays the burden of his mission on your shoulders. \r\n                But time is running out — will YOU take up the challenge?</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Caverns of the Snow Witch"
                        },
                        new
                        {
                            Id = 10L,
                            Code = "FF10",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>Taking refuge in the infamous House of Hell has to be the worst mistake of your life!</p>\r\n\r\n                <p>The dangers of the torrential storm outside are nothing compared to the blood-curdling adventures that await you inside. \r\n                Who knows how many hapless wanderers like yourself have perished within its gruesome walls? Be warned! Tonight is going to be a \r\n                night to remember ...</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "House of Hell"
                        },
                        new
                        {
                            Id = 11L,
                            Code = "FF11",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>The once-peaceful world of Orb is in terrible danger!</p>\r\n\r\n                <p>Dark forces are at work to unleash the awesome might of the Evil One, but their plans cannot be completed without the legendary \r\n                Talisman of Death. YOU are the one who carries the Talisman, and only YOU can stop the Dark forces. YOUR mission is to destroy the \r\n                Talisman before the dark lord's minions reach you. But beware! Time is running out!</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Talisman of Death"
                        },
                        new
                        {
                            Id = 12L,
                            Code = "FF12",
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "<p>A tyrannical despot is bent on destroying the world!</p>\r\n\r\n                <p>Looming above your home planet is the vast hulk of the starship Vandervecken. Aboard, the crazed scientist Cyrus is planning to \r\n                unleash a gruesome experiment upon your world, which will destroy all life as it is known, leaving only hideous mutations in its wake. \r\n                YOU are an assassin, and your mission is to stop him - before it is too late!</p>",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Space Assassin"
                        });
                });

            modelBuilder.Entity("FightingFantasy.Domain.Playthrough", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartParagraphId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("StartParagraphId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayThroughs");
                });

            modelBuilder.Entity("FightingFantasy.Domain.PlaythroughParagraph", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Items")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("ParagraphNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ToParagraphId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToParagraphId")
                        .IsUnique();

                    b.ToTable("PlayThroughParagraphs");
                });

            modelBuilder.Entity("FightingFantasy.Domain.PlaythroughStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PlaythroughParagraphId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaythroughParagraphId");

                    b.HasIndex("StatId");

                    b.ToTable("PlaythroughStat");
                });

            modelBuilder.Entity("FightingFantasy.Domain.Stat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookStats");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Skill"
                        },
                        new
                        {
                            Id = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Stamina"
                        },
                        new
                        {
                            Id = 3L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Luck"
                        },
                        new
                        {
                            Id = 4L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Provisions"
                        },
                        new
                        {
                            Id = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Magic"
                        },
                        new
                        {
                            Id = 6L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Weapons Strength"
                        },
                        new
                        {
                            Id = 7L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Shields"
                        },
                        new
                        {
                            Id = 8L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Gold"
                        },
                        new
                        {
                            Id = 9L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Fear"
                        },
                        new
                        {
                            Id = 10L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatName = "Pep Pills"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser<long>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FightingFantasy.Domain.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser<long>");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("BookStat", b =>
                {
                    b.HasOne("FightingFantasy.Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FightingFantasy.Domain.Stat", null)
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FightingFantasy.Domain.Playthrough", b =>
                {
                    b.HasOne("FightingFantasy.Domain.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId");

                    b.HasOne("FightingFantasy.Domain.PlaythroughParagraph", "StartParagraph")
                        .WithMany()
                        .HasForeignKey("StartParagraphId");

                    b.HasOne("FightingFantasy.Domain.User", null)
                        .WithMany("PlayThroughs")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("StartParagraph");
                });

            modelBuilder.Entity("FightingFantasy.Domain.PlaythroughParagraph", b =>
                {
                    b.HasOne("FightingFantasy.Domain.PlaythroughParagraph", "ToParagraph")
                        .WithOne()
                        .HasForeignKey("FightingFantasy.Domain.PlaythroughParagraph", "ToParagraphId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ToParagraph");
                });

            modelBuilder.Entity("FightingFantasy.Domain.PlaythroughStat", b =>
                {
                    b.HasOne("FightingFantasy.Domain.PlaythroughParagraph", null)
                        .WithMany("PlaythroughStats")
                        .HasForeignKey("PlaythroughParagraphId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FightingFantasy.Domain.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<long>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<long>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<long>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<long>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FightingFantasy.Domain.PlaythroughParagraph", b =>
                {
                    b.Navigation("PlaythroughStats");
                });

            modelBuilder.Entity("FightingFantasy.Domain.User", b =>
                {
                    b.Navigation("PlayThroughs");
                });
#pragma warning restore 612, 618
        }
    }
}
